apiVersion: v1
kind: Pod
metadata:
  name: shiva
  namespace: shiva
  labels:
    environment: dev
    project: roboshop
  annotations:
    description: This is a pod for shiva namespace
spec:
  containers:
  - name: nginx
    image: nginx
