apiVersion: v1
kind: Pod
metadata:
  name: shiva
  namespace: shiva
  labels:
    environment: dev
    project: roboshop
  annotations:
    description: This is a pod for shiva namespace
    url: https://www.facebook.com
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
      requests:
        memory: "64Mi"
        cpu: "250m"
