apiVersion: v1
kind: Service
metadata:
  name: nginx-np
spec:
  type: NodePort
  selector:
    project: roboshop
    component: frontend
    enironment: dev
    purpose: nodeport
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
