apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-service
  labels:
    project: roboshop
    component: frontend
    enironment: dev
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    