apiVersion: v1
kind: Pod
metadata:
  name: service-demo
  labels:
    roject: roboshop
    component: frontend
    enironment: dev
spec:
  containers:
  - name: nginx-container
    image: nginx:1.14.2