apiVersion: v1
kind: Pod
metadata:
  namespace: roboshop
  name: nginx-pod
  labels:
    app: nginx
spec:
  containers:
  - name: nginx-container
    image: nginx:1.14.2
    ports:
    - containerPort: 80