apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replicaset
  labels:
    app: nginx
spec:
  # number of desired pods
  replicas: 3
  # selector matches the labels on the Pod template
  selector:
    matchLabels:
      app: nginx
  # template for the pods to create
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
