apiVersion: v1
kind: Service
metadata:
  name: my-nginx-service
spec:
  selector:
    project: roboshop
    component: frontend
    enironment: dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80