apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx-html
    image: nginx  # Using Alpine for smaller footprint
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"  # 0.1 CPU cores
      limits:
        memory: "256Mi"
        cpu: "500m"  # 0.5 CPU cores
    volumeMounts:
    - name: ebs-nginx
      mountPath: /usr/share/nginx/html
    # Add health checks
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 15
      periodSeconds: 20
      timeoutSeconds: 5
      failureThreshold: 3
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 10
      timeoutSeconds: 3
      failureThreshold: 1
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1d
  volumes:
  - name: ebs-nginx
    persistentVolumeClaim:
      claimName: ebs-static-claim
