apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    purpose: ebs-static
spec:
  containers:
  - name: nginx-html
    image: nginx:1.14.2  # Using Alpine for smaller footprint
    volumeMounts:
    - name: ebs-nginx
      mountPath: /usr/share/nginx/html
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1d
  volumes:
  - name: ebs-nginx
    persistentVolumeClaim:
      claimName: ebs-static-claim

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-staticebslb-service
spec:
  type: LoadBalancer
  selector:
    purpose: ebs-static
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007
