apiVersion: v1
kind: Pod   
metadata:
  name: service-pod-nodeport
  labels:
    type: nodeport
    purpose: practice
    env: dev
    project: roboshop
spec:
  containers: 
  - name: nginx
    image: nginx