apiVersion: v1
kind: Pod   
metadata:
  name: nodeport-pod
  labels:
     purpose: practice
     env: dev
     project: nodeport
spec:
  containers: 
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80