apiVersion: v1
kind: Service
metadata: 
  name: ngninx-service
spec:
  selector:
    purpose: practice
    env: dev
    project: roboshop
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080