apiVersion: v1
kind: Service
metadata: 
  name: nodeport-service
spec:
  type: NodePort
  selector:
    purpose: practice
    env: dev
    project: nodeport
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30082