apiVersion: v1
kind: Pod
metadata:
  name: pod-config
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:
    - configMapRef:
        name: app-config
    ports:
    - containerPort: 80
      name: http  # Optional but recommended
      protocol: TCP